spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-lucky-king-ap5dlg9z-pooler.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE